import { createServer } from 'node:http';
import { createRehydraFetch } from '/private/tmp/claude-501/-Users-bytedance-ops/5a2992f0-ab38-4776-bf1e-a19fd1288dfb/scratchpad/rehydra-sdk/src/proxy/rehydra-fetch.ts';
import { InMemoryKeyProvider } from '/private/tmp/claude-501/-Users-bytedance-ops/5a2992f0-ab38-4776-bf1e-a19fd1288dfb/scratchpad/rehydra-sdk/src/crypto/index.ts';
import { InMemoryPIIStorageProvider } from '/private/tmp/claude-501/-Users-bytedance-ops/5a2992f0-ab38-4776-bf1e-a19fd1288dfb/scratchpad/rehydra-sdk/src/storage/in-memory.ts';
const srv = createServer(async (req,res)=>{let raw='';for await(const c of req)raw+=c; global.recv=JSON.parse(raw); res.writeHead(200,{'Content-Type':'application/json'}); res.end(JSON.stringify({choices:[{message:{role:'assistant',content:'ok'}}]}));});
await new Promise(r=>srv.listen(0,'127.0.0.1',r));
const port=srv.address().port;
const f=createRehydraFetch({keyProvider:new InMemoryKeyProvider(),piiStorageProvider:new InMemoryPIIStorageProvider(),provider:'openai',getSessionId:async()=>'s'});
await f(`http://127.0.0.1:${port}/v1/chat/completions`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({model:'test',messages:[{role:'user',content:'Email john@example.com'}]})});
console.log('upstream received content:', global.recv.messages[0].content);
srv.close();
